/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monitoringsystem;

import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;

/**
 *
 * @author mel
 */
public class Load extends javax.swing.JFrame {
    
    /**
     * Creates new form Load
     */
   MusicHelper mh = new MusicHelper();
    
   URL sounds, err, warnings, logouts,unsus, success, attemptload;
    
    
    public Load() {
        initComponents();
        
        newLoad();
        
        sounds = getClass().getResource("1lofi.wav");
        err = getClass().getResource("ERROR 1.4 SEC.wav");
        warnings = getClass().getResource("WARNING 1.1 SEC.wav");
        logouts = getClass().getResource("l_o.wav");
        unsus = getClass().getResource("unsuspicous.wav");
        success = getClass().getResource("final success.wav");
        attemptload = getClass().getResource("attemptloading.wav");
        
        
        this.setIconImage(new ImageIcon(getClass().getResource("log.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProgressBar1 = new javax.swing.JProgressBar();
        percent = new javax.swing.JLabel();
        val = new javax.swing.JLabel();
        loading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(654, 370));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProgressBar1.setFont(new java.awt.Font("Cambria Math", 1, 17)); // NOI18N
        jPanel1.add(ProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 280, 500, 20));

        percent.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        percent.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 330, 60, 20));

        val.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        val.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(val, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 324, 210, 30));

        loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monitoringsystem/icons/png/Splash1.png"))); // NOI18N
        jPanel1.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

       
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            
            Load p = new Load();
            p.setVisible(true);
            
          
            
            
        
        //</editor-fold>
        
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loading;
    private javax.swing.JLabel percent;
    private javax.swing.JLabel val;
    // End of variables declaration//GEN-END:variables
private void newLoad(){
    new Thread(new Runnable() {
        @Override
        public void run() {
        try{
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            
            try{
                for(int i = 0; i <= 100; i ++){
                    Thread.sleep(45);
                    percent.setText(i + "%");
                    
                    if(i ==3){
                        val.setText("Initializing Data......");
                        mh.logoutBg(logouts);
                    }
                    if(i ==25){
                        val.setText("Starting Database......");
                    }
                    if(i ==45){
                        val.setText("Loading GUI Application......");
                    }
                    if(i ==65){
                        val.setText("Preaparing Connection.....");
                    }
                    if(i ==70){
                        val.setText("Connnection Successful.....");
                    }
                    if(i ==82){
                        val.setText("Generating Attendance.....");
                    }
                    if(i ==93){
                        val.setText("Loading Complete");
                    }
                    if(i ==100){
                        val.setText("Welcome to Login System");
                    }
                    ProgressBar1.setValue(i);
                    
                }
            } catch (InterruptedException | UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
                Logger.getLogger(Load.class.getName()).log(Level.SEVERE, null, ex);
            }
            Home m = new Home();
            m.setVisible(true);
            dispose();
            mh.playbg1(sounds);
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
                Logger.getLogger(Load.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }).start();
}


}
