/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monitoringsystem;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author mel
 */
public class Load3 extends javax.swing.JFrame {

    /**
     * Creates new form Load3
     */
    
    MusicHelper mh = new MusicHelper();
    
    URL sounds, err, warnings, logouts,unsus, success, attemptload;
    
    
    public Load3() {
        initComponents();
        munumuni();
        
        sounds = getClass().getResource("1lofi.wav");
        err = getClass().getResource("ERROR 1.4 SEC.wav");
        warnings = getClass().getResource("WARNING 1.1 SEC.wav");
        logouts = getClass().getResource("l_o.wav");
        unsus = getClass().getResource("unsuspicous.wav");
        success = getClass().getResource("final success.wav");
        attemptload = getClass().getResource("attemptloading.wav");
        
        this.setIconImage(new ImageIcon(getClass().getResource("log.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        val = new javax.swing.JLabel();
        percent = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 280, 500, 20));

        val.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        val.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(val, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 270, 20));

        percent.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        percent.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 60, 20));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monitoringsystem/icons/png/Splash1.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Load3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Load3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Load3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Load3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Load3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel percent;
    private javax.swing.JLabel val;
    // End of variables declaration//GEN-END:variables
public void munumuni(){
    new Thread(new Runnable() {
        @Override
        public void run() {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
        
            try {
                for (int i = 0; i <101; i++){
                Thread.sleep(65);
                percent.setText(i + "%");
                
                if(i==0){
                    mh.attmptBg(attemptload);
                }
                if(i ==3){
                     val.setText("Turning off Modules......");
                     
                }
                if(i ==25){
                     val.setText("Stopping Database......");
                }
                if(i ==45){
                     val.setText("Logging out Student......");
                }
                if(i ==65){
                     val.setText("Removing Connection.....");
                }
                if(i ==70){
                     val.setText("Disconnecting to Server.....");
                }
                if(i ==80){
                     val.setText("Connection Error.....");
                }
                if(i ==91){
                     val.setText("Student Not Found");
                }
                if(i ==100){
                   val.setText("Login System Disabled"); 
                   mh.popUpMusic();
                }
                jProgressBar1.setValue(i);    
            }   
            } catch (Exception e) {
                
            }
            Attempt a = new Attempt();
            a.setVisible(true);
            dispose();
        }
    }).start();
}
}
