/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monitoringsystem;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mel
 */
public class logLoad extends javax.swing.JFrame {

    /**
     * Creates new form logLoad
     */
    
    MusicHelper mh = new MusicHelper();
    
    URL sounds, err, warnings, logouts,unsus, success, attemptload;
    
    public logLoad() {
        initComponents();
        loading();
        
        sounds = getClass().getResource("1lofi.wav");
        err = getClass().getResource("ERROR 1.4 SEC.wav");
        warnings = getClass().getResource("WARNING 1.1 SEC.wav");
        logouts = getClass().getResource("l_o.wav");
        unsus = getClass().getResource("unsuspicous.wav");
        success = getClass().getResource("final success.wav");
        attemptload = getClass().getResource("attemptloading.wav");
        
        this.setIconImage(new ImageIcon(getClass().getResource("log.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        val = new javax.swing.JLabel();
        percent = new javax.swing.JLabel();
        splash = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setForeground(new java.awt.Color(153, 153, 0));
        jProgressBar1.setBorderPainted(false);
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 280, 500, 20));

        val.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        val.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(val, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 270, 20));

        percent.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        percent.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 60, 20));

        splash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monitoringsystem/icons/png/Splash1.png"))); // NOI18N
        getContentPane().add(splash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 350));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 650, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        logLoad l = new logLoad();
        l.setVisible(true);  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel percent;
    private javax.swing.JLabel splash;
    private javax.swing.JLabel val;
    // End of variables declaration//GEN-END:variables
private void loading(){
    new Thread(new Runnable() {
        @Override
        public void run() {
            
            Logout t = new Logout();
          
            try {
                for (int i = 0; i <101; i++){
                Thread.sleep(45);
                percent.setText(i + "%");
                
                if(i ==5){
                     val.setText("Turning off Modules......");
                     MusicHelper.logoutBg(logouts);
                }
                if(i ==25){
                     val.setText("Stopping Database......");
                }
                if(i ==45){
                     val.setText("Logging out Student......");
                }
                if(i ==65){
                     val.setText("Removing Connection.....");
                }
                if(i ==70){
                     val.setText("Disconnecting to Server.....");
                }
                if(i ==80){
                     val.setText("Generating Logout Page.....");
                }
                if(i ==91){
                     val.setText("Logout Complete");
                }
                if(i ==100){
                   val.setText("Welcome to Logout Page");  
                }
                jProgressBar1.setValue(i);    
            }   
            } catch (Exception e) {
                
            }
            t.setVisible(true);
            dispose();
            }       
    }).start();
}
}
